### ISSUE TITLE
Problem with EOL API module

### ISSUE THREAD

**Issue by Sufrostico** [gbif/gbif-npt-startup#6]
The images from EOL in the banner area does not work, or in the front page does not work.

Return error message:
Fatal error: Call to undefined method stdClass::render() in /var/www/npt.inbio.ac.cr/sites/all/modules/custom/eolapi/eolapi.ajax.inc on line 18

Problem:
The module seems unable to found the view because  $_POST['view-name'] comes empty.

by changing the variable from: $_POST['view-name'] to $_POST['viewName'] fixes the problem. 

![eolapi](https://f.cloud.github.com/assets/1326163/1027187/696bd640-0e6c-11e3-8f16-3013c9311104.png)

using NPT from truck with date: August 19, 2013

**Comment by ckotwn** [comment]
Good find. I suppose that error message appears only before importing the checklist. Have you tried whether this fix has any influence on the importing or EOL content retrieving?

**Comment by Sufrostico** [comment]
Just test this.

With the change the images, and the description are imported from EOL without problems after y visiting the media tab in the species menu option.

URL example: http://npt.inbio.ac.cr/taxonomy/term/11/media
